### ISSUE TITLE
Too Long Function process_quorums()

### ISSUE THREAD

**Issue by codeman-crypto** [Beldex-Coin/beldex#68]
The function ```process_quorums()``` in [master_node_quorum_cop.cpp#L234](https://github.com/Beldex-Coin/beldex/blob/master/src/cryptonote_core/master_node_quorum_cop.cpp#L234) is too long, making it difficult to read and understand. In particular, many (logically) different actions are performed, which could be added into a separate function and called by ```process_quorums()```.

**Comment by chitrasenthil** [comment]
Excelent , great.. Thank you

**Comment by victor-tucci** [comment]
Since the function process_quorums() is too long. The function can be breakdown into three functions.
These functions could have the following names and those are,
void quorum_checkpoint_handle();
void handling_master_nodes_states();
void handling_my_master_node_states();  
May i proceed with these functions.

**Comment by codeman-crypto** [comment]
Go ahead.. Make sure it doesn't break the functionality

**Comment by victor-tucci** [comment]
This breakdown function can increase the readability. Added the pull request #76
